### ISSUE TITLE
OWLViz generates empty, editable error window, if dot is not found

### ISSUE THREAD

**Issue by tudorache** [protegeproject/owlviz#10] opened 2016-05-03 19:01 UTC
If OWLViz will not find dot, it will generate an empty error window that is editable. The error window is very big, its size should also be reduced. The error window is not resizable.
See also first error being thrown.

![owlviz](https://cloud.githubusercontent.com/assets/2709502/14994827/9f1c8b94-1126-11e6-8db5-957244965ea6.png)

```
C:\Users\ttania\Desktop\Protege-5.0.0-RC1-SNAPSHOT>setlocal

C:\Users\ttania\Desktop\Protege-5.0.0-RC1-SNAPSHOT>cd /d C:\Users\ttania\Desktop\Protege-5.0.0-RC1-SNAPSHOT\

C:\Users\ttania\Desktop\Protege-5.0.0-RC1-SNAPSHOT>jre\bin\java -Xmx500M -Xms200M -XX:CompileCommand=exclude,javax/swing/text/GlyphView,getBreakSpot -DentityExpansionLimit=100000000 -Dlogback.configurationFile=conf/logback-win.xml -Dfile.encoding=utf-8 -Dorg.protege.plugin.dir=plugins -classpath bundles/guava.jar;bundles/logback-classic.jar;bundles/logback-core.jar;bundles/slf4j-api.jar;bin/org.apache.felix.main.jar;bin/protege-launcher.jar org.protege.osgi.framework.Launcher
CompilerOracle: exclude javax/swing/text/GlyphView.getBreakSpot
********************************************************************************
**                                  Protege                                   **
********************************************************************************

----------------- Initialising and Starting the OSGi Framework -----------------
FrameworkFactory Class: org.apache.felix.framework.FrameworkFactory

The OSGi framework has been initialised
------------------------------- Starting Bundles -------------------------------
Starting bundle org.protege.common
Starting bundle org.eclipse.equinox.common
Starting bundle org.eclipse.equinox.supplement
Starting bundle org.eclipse.equinox.registry
Starting bundle org.protege.editor.core.application
Starting bundle org.apache.commons.io
Starting bundle com.google.guava
Not starting bundle com.google.inject.assistedinject explicitly because it is a fragment bundle.
Not starting bundle com.google.inject.multibindings explicitly because it is a fragment bundle.
Starting bundle com.google.inject
Starting bundle jul.to.slf4j
Starting bundle log4j.over.slf4j
Starting bundle ch.qos.logback.classic
Starting bundle ch.qos.logback.core
Starting bundle org.apache.servicemix.bundles.aopalliance
Starting bundle org.apache.servicemix.bundles.javax-inject
Starting bundle org.eclipse.equinox.common
Starting bundle org.eclipse.equinox.registry
Starting bundle org.eclipse.equinox.supplement
Starting bundle org.semanticweb.owl.owlapi
Starting bundle org.protege.common
Starting bundle org.protege.editor.core.application
Starting bundle org.protege.editor.owl
Starting bundle slf4j.api
Starting bundle cellfie
Starting bundle code-generation
Starting bundle com.clarkparsia.protege.plugin.pellet
Starting bundle existentialquery
Starting bundle uk.ac.manchester.cs.owl.explanation
Starting bundle org.protege.ontograf
Starting bundle org.coode.change
Starting bundle org.coode.dlquery
Starting bundle org.protege.editor.owl.diff
Starting bundle org.semanticweb.hermit
Starting bundle org.coode.browser
Starting bundle org.coode.owlviz
Starting bundle org.protege.owl.rdf
Starting bundle snap-sparql-query-plugin
Starting bundle org.protege.editor.owl.rdf
Starting bundle swrltab-plugin
Starting bundle uk.ac.manchester.cs.owl.factplusplus
The OSGi framework has been started
------------------------------------ Prot├⌐g├⌐ -----------------------------------

Prot├⌐g├⌐ Desktop
Version 5.0.0, Build RC1-SNAPSHOT


----------------------------------- Platform -----------------------------------
Java: JVM 1.8.0_40-b26  Memory: 466M
Language: en, Country: US
Framework: Apache Software Foundation (1.7)
OS: windows8 (6.3)
Processor: x86-64


------------------------------------ Plugins -----------------------------------
Plugin: Cellfie Protege 5.0+ Plugin (2.0.0.beta-7)
Plugin: OWL Code Generation Plug-in (2.0.0)
Plugin: Pellet Reasoner Plug-in (2.2.0)
Plugin: Existential Query (2.0.0)
Plugin: Explanation Workbench (3.0.0)
Plugin: OntoGraf (2.0.2)
Plugin: Change Tracker (2.0.2)
Plugin: DL Query (3.0.1)
Plugin: OWL Difference (6.0.2)
Plugin: HermiT (1.3.8.413)
Plugin: OWLDoc (3.0.2)
Plugin: OWLViz (5.0.1)
Plugin: OWLAPI RDF Library (2.0.2)
Plugin: snap-sparql-query-plugin (4.1.0)
Plugin: Protege SPARQL Plugin (2.0.1)
Plugin: SWRLTab Protege 5.0+ Plugin (1.0.0.beta-52)
Plugin: Factplusplus Plug-in (1.6.4)

        OWLAPI RDF Library Plugin has no plugin.xml resource
May 03, 2016 11:49:52 AM java.util.prefs.WindowsPreferences <init>
WARNING: Could not open/create prefs root node Software\JavaSoft\Prefs at root 0x80000002. Windows RegCreateKeyEx(...) returned error code 5.
OWL API Version: 4.2.3.20160319-0906
Cannot generate ontology catalog for ontology at http://www.semanticweb.org/ttania/ontologies/2016/4/untitled-ontology-17
### Excluding compile: javax.swing.text.GlyphView::getBreakSpot
------------------------------- Auto-update Check ------------------------------
Auto-update last performed: Fri Apr 29 11:50:49 PDT 2016
Auto-update has not been performed today.  Running it.

------------------------------ Running Auto-update -----------------------------

--- Searching for plugins ---
Checking https://raw.githubusercontent.com/protegeproject/autoupdate/master/update-info/5.0.0/plugins.repository
    Processing https://raw.githubusercontent.com/protegeproject/autoupdate/master/update-info/5.0.0/plugins.repository as a plugin registry
        Checking https://raw.githubusercontent.com/protegeproject/cellfie-plugin/master/update-info/protege-5/update.properties
        Checking https://raw.githubusercontent.com/co-ode-owl-plugins/change-tracker/master/update-info/protege-5/update.properties
        Checking https://raw.githubusercontent.com/protegeproject/dlquery/master/update-info/protege-5/update.properties
        Checking http://elk.semanticweb.org/maven/latest/elk-distribution/resources/p5.update.properties
        Checking https://raw.githubusercontent.com/protegeproject/existentialquery/master/update-info/protege-5/update.properties
        Checking https://bitbucket.org/dtsarkov/factplusplus/downloads/config.autoupdate.Protege-5.0.txt
        Checking https://raw.githubusercontent.com/julianmendez/jcel/master/update-info/protege-5/update.properties
        Checking https://raw.githubusercontent.com/protegeproject/ontograf/master/update-info/protege-5/update.properties
        Checking https://github.com/ontop/ontop/raw/master/ontop-protege/update.properties
        Checking https://raw.githubusercontent.com/protegeproject/rdf-library/master/update-info/protege-5/update.properties
        Checking https://raw.githubusercontent.com/protegeproject/owl-diff/master/update-info/protege-5/update.properties
        Checking https://raw.githubusercontent.com/co-ode-owl-plugins/owldoc/master/update-info/protege-5/update.properties
        Checking https://raw.githubusercontent.com/protegeproject/owlviz/master/update-info/protege-5/update.properties 
        Checking https://raw.githubusercontent.com/Complexible/pellet/master/protege/plugin/plugins.repository
            Processing https://raw.githubusercontent.com/Complexible/pellet/master/protege/plugin/plugins.repository as a plugin registry
                Checking https://raw.githubusercontent.com/Complexible/pellet/master/protege/plugin/update.properties
        Checking https://raw.githubusercontent.com/protegeproject/autoupdate/master/snap-sparql-query/update-info/protege-5/update.properties
        Checking https://raw.githubusercontent.com/protegeproject/sparql-query-plugin/master/update-info/protege-5/update.properties
        Checking https://raw.githubusercontent.com/protegeproject/swrltab-plugin/master/update-info/protege-5/update.properties

An error related to DOT has occurred. This error was probably because OWLViz could not find the DOT application.  Please ensure that the path to the DOT application is set properly
An error was thrown: An error related to DOT has occurred. This error was probably because OWLViz could not find the DOT application.  Please ensure that the path to the DOT application is set properly
org.coode.owlviz.util.graph.layout.dotlayoutengine.DotProcessException: An error related to DOT has occurred. This error was probably because OWLViz could not find the DOT application.  Please ensure that the path to the DOT application is set properly
        at org.coode.owlviz.util.graph.layout.dotlayoutengine.DotProcess.startProcess(DotProcess.java:80) [owlviz-5.0.1.jar:na]
        at org.coode.owlviz.util.graph.layout.dotlayoutengine.DotGraphLayoutEngine.layoutGraph(DotGraphLayoutEngine.java:98) [owlviz-5.0.1.jar:na]
        at org.coode.owlviz.util.graph.ui.GraphView.revalidateGraph(GraphView.java:312) [owlviz-5.0.1.jar:na]
        at org.coode.owlviz.util.graph.ui.GraphView$4.hierarchyChanged(GraphView.java:160) [owlviz-5.0.1.jar:na]
        at java.awt.Component.processHierarchyEvent(Component.java:6692) [na:1.8.0_40]
        at java.awt.Component.processEvent(Component.java:6311) [na:1.8.0_40]
        at java.awt.Container.processEvent(Container.java:2234) [na:1.8.0_40]
        at java.awt.Component.dispatchEventImpl(Component.java:4881) [na:1.8.0_40]
        at java.awt.Container.dispatchEventImpl(Container.java:2292) [na:1.8.0_40]
        at java.awt.Component.dispatchEvent(Component.java:4703) [na:1.8.0_40]
        at java.awt.Component.createHierarchyEvents(Component.java:5541) [na:1.8.0_40]
        at java.awt.Container.createHierarchyEvents(Container.java:1443) [na:1.8.0_40]
        at java.awt.Container.addImpl(Container.java:1139) [na:1.8.0_40]
        at javax.swing.JViewport.setView(JViewport.java:962) [na:1.8.0_40]
        at javax.swing.JScrollPane.setViewportView(JScrollPane.java:1007) [na:1.8.0_40]
        at javax.swing.JScrollPane.<init>(JScrollPane.java:302) [na:1.8.0_40]
        at javax.swing.JScrollPane.<init>(JScrollPane.java:323) [na:1.8.0_40]
        at org.coode.owlviz.util.graph.ui.GraphComponent.<init>(GraphComponent.java:65) [owlviz-5.0.1.jar:na]
        at org.coode.owlviz.ui.OWLVizGraphPanel.<init>(OWLVizGraphPanel.java:70) [owlviz-5.0.1.jar:na]
        at org.coode.owlviz.ui.OWLVizView.createOWLVizTabUI(OWLVizView.java:175) [owlviz-5.0.1.jar:na]
        at org.coode.owlviz.ui.OWLVizView.initialiseClassView(OWLVizView.java:109) [owlviz-5.0.1.jar:na]
        at org.protege.editor.owl.ui.view.cls.AbstractOWLClassViewComponent.initialiseView(AbstractOWLClassViewComponent.java:28) [protege-editor-owl.jar:na]
        at org.protege.editor.owl.ui.view.AbstractOWLSelectionViewComponent.initialiseOWLView(AbstractOWLSelectionViewComponent.java:98) [protege-editor-owl.jar:na]
        at org.protege.editor.owl.ui.view.AbstractOWLViewComponent.initialise(AbstractOWLViewComponent.java:46) [protege-editor-owl.jar:na]
        at org.protege.editor.core.ui.view.View.createContent(View.java:424) [protege-editor-core.jar:na]
        at org.protege.editor.core.ui.view.View.createUI(View.java:217) [protege-editor-core.jar:na]
        at org.protege.editor.core.ui.view.View$1.hierarchyChanged(View.java:123) [protege-editor-core.jar:na]
        at java.awt.Component.processHierarchyEvent(Component.java:6692) [na:1.8.0_40]
        at java.awt.Component.processEvent(Component.java:6311) [na:1.8.0_40]
        at java.awt.Container.processEvent(Container.java:2234) [na:1.8.0_40]
        at java.awt.Component.dispatchEventImpl(Component.java:4881) [na:1.8.0_40]
        at java.awt.Container.dispatchEventImpl(Container.java:2292) [na:1.8.0_40]
        at java.awt.Component.dispatchEvent(Component.java:4703) [na:1.8.0_40]
        at java.awt.Component.createHierarchyEvents(Component.java:5541) [na:1.8.0_40]
        at java.awt.Container.createHierarchyEvents(Container.java:1443) [na:1.8.0_40]
        at java.awt.Container.createHierarchyEvents(Container.java:1439) [na:1.8.0_40]
        at java.awt.Container.createHierarchyEvents(Container.java:1439) [na:1.8.0_40]
        at java.awt.Container.createHierarchyEvents(Container.java:1439) [na:1.8.0_40]
        at java.awt.Container.createHierarchyEvents(Container.java:1439) [na:1.8.0_40]
        at java.awt.Component.show(Component.java:1622) [na:1.8.0_40]
        at java.awt.Component.show(Component.java:1654) [na:1.8.0_40]
        at java.awt.Component.setVisible(Component.java:1606) [na:1.8.0_40]
        at javax.swing.JComponent.setVisible(JComponent.java:2644) [na:1.8.0_40]
        at javax.swing.JTabbedPane.fireStateChanged(JTabbedPane.java:394) [na:1.8.0_40]
        at javax.swing.JTabbedPane$ModelListener.stateChanged(JTabbedPane.java:270) [na:1.8.0_40]
        at javax.swing.DefaultSingleSelectionModel.fireStateChanged(DefaultSingleSelectionModel.java:132) [na:1.8.0_40]
        at javax.swing.DefaultSingleSelectionModel.setSelectedIndex(DefaultSingleSelectionModel.java:67) [na:1.8.0_40]
        at javax.swing.JTabbedPane.setSelectedIndexImpl(JTabbedPane.java:616) [na:1.8.0_40]
        at javax.swing.JTabbedPane.setSelectedIndex(JTabbedPane.java:591) [na:1.8.0_40]
        at javax.swing.plaf.basic.BasicTabbedPaneUI$Handler.mousePressed(BasicTabbedPaneUI.java:3647) [na:1.8.0_40]
        at java.awt.AWTEventMulticaster.mousePressed(AWTEventMulticaster.java:280) [na:1.8.0_40]
        at java.awt.AWTEventMulticaster.mousePressed(AWTEventMulticaster.java:279) [na:1.8.0_40]
        at java.awt.Component.processMouseEvent(Component.java:6522) [na:1.8.0_40]
        at javax.swing.JComponent.processMouseEvent(JComponent.java:3324) [na:1.8.0_40]
        at java.awt.Component.processEvent(Component.java:6290) [na:1.8.0_40]
        at java.awt.Container.processEvent(Container.java:2234) [na:1.8.0_40]
        at java.awt.Component.dispatchEventImpl(Component.java:4881) [na:1.8.0_40]
        at java.awt.Container.dispatchEventImpl(Container.java:2292) [na:1.8.0_40]
        at java.awt.Component.dispatchEvent(Component.java:4703) [na:1.8.0_40]
        at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4898) [na:1.8.0_40]
        at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4530) [na:1.8.0_40]
        at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4462) [na:1.8.0_40]
        at java.awt.Container.dispatchEventImpl(Container.java:2278) [na:1.8.0_40]
        at java.awt.Window.dispatchEventImpl(Window.java:2750) [na:1.8.0_40]
        at java.awt.Component.dispatchEvent(Component.java:4703) [na:1.8.0_40]
        at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:751) [na:1.8.0_40]
        at java.awt.EventQueue.access$500(EventQueue.java:97) [na:1.8.0_40]
        at java.awt.EventQueue$3.run(EventQueue.java:702) [na:1.8.0_40]
        at java.awt.EventQueue$3.run(EventQueue.java:696) [na:1.8.0_40]
        at java.security.AccessController.doPrivileged(Native Method) [na:1.8.0_40]
        at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75) [na:1.8.0_40]
        at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:86) [na:1.8.0_40]
        at java.awt.EventQueue$4.run(EventQueue.java:724) [na:1.8.0_40]
        at java.awt.EventQueue$4.run(EventQueue.java:722) [na:1.8.0_40]
        at java.security.AccessController.doPrivileged(Native Method) [na:1.8.0_40]
        at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75) [na:1.8.0_40]
        at java.awt.EventQueue.dispatchEvent(EventQueue.java:721) [na:1.8.0_40]
        at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201) [na:1.8.0_40]
        at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116) [na:1.8.0_40]
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105) [na:1.8.0_40]
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101) [na:1.8.0_40]
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93) [na:1.8.0_40]
        at java.awt.EventDispatchThread.run(EventDispatchThread.java:82) [na:1.8.0_40]
Caused by: java.io.IOException: Cannot run program "C:\Program Files (x86)\Graphviz2.30\bin\dot.exe": CreateProcess error=2, The system cannot find the file specified
        at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048) ~[na:1.8.0_40]
        at java.lang.Runtime.exec(Runtime.java:620) ~[na:1.8.0_40]
        at java.lang.Runtime.exec(Runtime.java:485) ~[na:1.8.0_40]
        at org.coode.owlviz.util.graph.layout.dotlayoutengine.DotProcess.startProcess(DotProcess.java:60) [owlviz-5.0.1.jar:na]
        ... 82 common frames omitted
Caused by: java.io.IOException: CreateProcess error=2, The system cannot find the file specified
        at java.lang.ProcessImpl.create(Native Method) ~[na:1.8.0_40]
        at java.lang.ProcessImpl.<init>(ProcessImpl.java:386) ~[na:1.8.0_40]
        at java.lang.ProcessImpl.start(ProcessImpl.java:137) ~[na:1.8.0_40]
        at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029) ~[na:1.8.0_40]
        ... 85 common frames omitted
Uncaught Exception in thread 'AWT-EventQueue-0'
java.lang.ArrayIndexOutOfBoundsException: -1
        at javax.swing.plaf.basic.BasicTabbedPaneUI.getTabBounds(BasicTabbedPaneUI.java:1534) ~[na:1.8.0_40]
        at javax.swing.plaf.basic.BasicTabbedPaneUI.getTabBounds(BasicTabbedPaneUI.java:1469) ~[na:1.8.0_40]
        at org.protege.editor.core.ui.tabbedpane.CloseableTabbedPaneUI.getTabBounds(CloseableTabbedPaneUI.java:234) ~[protege-editor-core.jar:na]
        at org.protege.editor.core.ui.tabbedpane.CloseableTabbedPaneUI.paintContentBorderTopEdge(CloseableTabbedPaneUI.java:361) ~[protege-editor-core.jar:na]
        at javax.swing.plaf.basic.BasicTabbedPaneUI.paintContentBorder(BasicTabbedPaneUI.java:1315) ~[na:1.8.0_40]
        at javax.swing.plaf.basic.BasicTabbedPaneUI.paint(BasicTabbedPaneUI.java:800) ~[na:1.8.0_40]
        at javax.swing.plaf.ComponentUI.update(ComponentUI.java:161) ~[na:1.8.0_40]
        at javax.swing.JComponent.paintComponent(JComponent.java:780) [na:1.8.0_40]
        at javax.swing.JComponent.paint(JComponent.java:1056) [na:1.8.0_40]
        at javax.swing.JComponent.paintChildren(JComponent.java:889) [na:1.8.0_40]
        at javax.swing.JComponent.paint(JComponent.java:1065) [na:1.8.0_40]
        at javax.swing.JComponent.paintChildren(JComponent.java:889) [na:1.8.0_40]
        at javax.swing.JComponent.paint(JComponent.java:1065) [na:1.8.0_40]
        at javax.swing.JComponent.paintChildren(JComponent.java:889) [na:1.8.0_40]
        at javax.swing.JComponent.paint(JComponent.java:1065) [na:1.8.0_40]
        at javax.swing.JComponent.paintChildren(JComponent.java:889) [na:1.8.0_40]
        at javax.swing.JComponent.paint(JComponent.java:1065) [na:1.8.0_40]
        at javax.swing.JComponent.paintChildren(JComponent.java:889) [na:1.8.0_40]
        at javax.swing.JComponent.paint(JComponent.java:1065) [na:1.8.0_40]
        at javax.swing.JComponent.paintChildren(JComponent.java:889) [na:1.8.0_40]
        at javax.swing.JComponent.paint(JComponent.java:1065) [na:1.8.0_40]
        at javax.swing.JComponent.paintChildren(JComponent.java:889) [na:1.8.0_40]
        at javax.swing.JComponent.paint(JComponent.java:1065) [na:1.8.0_40]
        at javax.swing.JComponent.paintChildren(JComponent.java:889) [na:1.8.0_40]
        at javax.swing.JComponent.paint(JComponent.java:1065) [na:1.8.0_40]
        at javax.swing.JComponent.paintChildren(JComponent.java:889) [na:1.8.0_40]
        at javax.swing.JComponent.paint(JComponent.java:1065) [na:1.8.0_40]
        at javax.swing.JComponent.paintChildren(JComponent.java:889) [na:1.8.0_40]
        at javax.swing.JSplitPane.paintChildren(JSplitPane.java:1047) ~[na:1.8.0_40]
        at javax.swing.JComponent.paint(JComponent.java:1065) [na:1.8.0_40]
        at javax.swing.JComponent.paintToOffscreen(JComponent.java:5219) [na:1.8.0_40]
        at javax.swing.RepaintManager$PaintManager.paintDoubleBuffered(RepaintManager.java:1572) ~[na:1.8.0_40]
        at javax.swing.RepaintManager$PaintManager.paint(RepaintManager.java:1495) ~[na:1.8.0_40]
        at javax.swing.RepaintManager.paint(RepaintManager.java:1265) ~[na:1.8.0_40]
        at javax.swing.JComponent._paintImmediately(JComponent.java:5167) [na:1.8.0_40]
        at javax.swing.JComponent.paintImmediately(JComponent.java:4978) [na:1.8.0_40]
        at javax.swing.RepaintManager$4.run(RepaintManager.java:824) ~[na:1.8.0_40]
        at javax.swing.RepaintManager$4.run(RepaintManager.java:807) ~[na:1.8.0_40]
        at java.security.AccessController.doPrivileged(Native Method) [na:1.8.0_40]
        at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75) [na:1.8.0_40]
        at javax.swing.RepaintManager.paintDirtyRegions(RepaintManager.java:807) ~[na:1.8.0_40]
        at javax.swing.RepaintManager.paintDirtyRegions(RepaintManager.java:782) ~[na:1.8.0_40]
        at javax.swing.RepaintManager.prePaintDirtyRegions(RepaintManager.java:731) ~[na:1.8.0_40]
        at javax.swing.RepaintManager.access$1300(RepaintManager.java:64) ~[na:1.8.0_40]
        at javax.swing.RepaintManager$ProcessingRunnable.run(RepaintManager.java:1720) ~[na:1.8.0_40]
        at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311) ~[na:1.8.0_40]
        at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:749) [na:1.8.0_40]
        at java.awt.EventQueue.access$500(EventQueue.java:97) [na:1.8.0_40]
        at java.awt.EventQueue$3.run(EventQueue.java:702) [na:1.8.0_40]
        at java.awt.EventQueue$3.run(EventQueue.java:696) [na:1.8.0_40]
        at java.security.AccessController.doPrivileged(Native Method) [na:1.8.0_40]
        at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75) [na:1.8.0_40]
        at java.awt.EventQueue.dispatchEvent(EventQueue.java:719) [na:1.8.0_40]
        at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201) [na:1.8.0_40]
        at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116) [na:1.8.0_40]
        at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:109) [na:1.8.0_40]
        at java.awt.WaitDispatchSupport$2.run(WaitDispatchSupport.java:184) [na:1.8.0_40]
        at java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:229) [na:1.8.0_40]
        at java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:227) [na:1.8.0_40]
        at java.security.AccessController.doPrivileged(Native Method) [na:1.8.0_40]
        at java.awt.WaitDispatchSupport.enter(WaitDispatchSupport.java:227) [na:1.8.0_40]
        at java.awt.Dialog.show(Dialog.java:1084) [na:1.8.0_40]
        at javax.swing.JOptionPane.showOptionDialog(JOptionPane.java:869) [na:1.8.0_40]
        at javax.swing.JOptionPane.showMessageDialog(JOptionPane.java:666) [na:1.8.0_40]
        at javax.swing.JOptionPane.showMessageDialog(JOptionPane.java:637) [na:1.8.0_40]
        at org.protege.editor.core.ui.error.ErrorLogPanel.showErrorDialog(ErrorLogPanel.java:102) [protege-editor-core.jar:na]
        at org.coode.owlviz.util.graph.layout.dotlayoutengine.DotProcess.startProcess(DotProcess.java:80) [owlviz-5.0.1.jar:na]
        at org.coode.owlviz.util.graph.layout.dotlayoutengine.DotGraphLayoutEngine.layoutGraph(DotGraphLayoutEngine.java:98) [owlviz-5.0.1.jar:na]
        at org.coode.owlviz.util.graph.ui.GraphView.revalidateGraph(GraphView.java:312) [owlviz-5.0.1.jar:na]
        at org.coode.owlviz.util.graph.ui.GraphView$4.hierarchyChanged(GraphView.java:160) [owlviz-5.0.1.jar:na]
        at java.awt.Component.processHierarchyEvent(Component.java:6692) [na:1.8.0_40]
        at java.awt.Component.processEvent(Component.java:6311) [na:1.8.0_40]
        at java.awt.Container.processEvent(Container.java:2234) [na:1.8.0_40]
        at java.awt.Component.dispatchEventImpl(Component.java:4881) [na:1.8.0_40]
        at java.awt.Container.dispatchEventImpl(Container.java:2292) [na:1.8.0_40]
        at java.awt.Component.dispatchEvent(Component.java:4703) [na:1.8.0_40]
        at java.awt.Component.createHierarchyEvents(Component.java:5541) [na:1.8.0_40]
        at java.awt.Container.createHierarchyEvents(Container.java:1443) [na:1.8.0_40]
        at java.awt.Container.addImpl(Container.java:1139) [na:1.8.0_40]
        at javax.swing.JViewport.setView(JViewport.java:962) [na:1.8.0_40]
        at javax.swing.JScrollPane.setViewportView(JScrollPane.java:1007) [na:1.8.0_40]
        at javax.swing.JScrollPane.<init>(JScrollPane.java:302) [na:1.8.0_40]
        at javax.swing.JScrollPane.<init>(JScrollPane.java:323) [na:1.8.0_40]
        at org.coode.owlviz.util.graph.ui.GraphComponent.<init>(GraphComponent.java:65) [owlviz-5.0.1.jar:na]
        at org.coode.owlviz.ui.OWLVizGraphPanel.<init>(OWLVizGraphPanel.java:70) [owlviz-5.0.1.jar:na]
        at org.coode.owlviz.ui.OWLVizView.createOWLVizTabUI(OWLVizView.java:175) [owlviz-5.0.1.jar:na]
        at org.coode.owlviz.ui.OWLVizView.initialiseClassView(OWLVizView.java:109) [owlviz-5.0.1.jar:na]
        at org.protege.editor.owl.ui.view.cls.AbstractOWLClassViewComponent.initialiseView(AbstractOWLClassViewComponent.java:28) [protege-editor-owl.jar:na]
        at org.protege.editor.owl.ui.view.AbstractOWLSelectionViewComponent.initialiseOWLView(AbstractOWLSelectionViewComponent.java:98) [protege-editor-owl.jar:na]
        at org.protege.editor.owl.ui.view.AbstractOWLViewComponent.initialise(AbstractOWLViewComponent.java:46) [protege-editor-owl.jar:na]
        at org.protege.editor.core.ui.view.View.createContent(View.java:424) [protege-editor-core.jar:na]
        at org.protege.editor.core.ui.view.View.createUI(View.java:217) [protege-editor-core.jar:na]
        at org.protege.editor.core.ui.view.View$1.hierarchyChanged(View.java:123) [protege-editor-core.jar:na]
        at java.awt.Component.processHierarchyEvent(Component.java:6692) [na:1.8.0_40]
        at java.awt.Component.processEvent(Component.java:6311) [na:1.8.0_40]
        at java.awt.Container.processEvent(Container.java:2234) [na:1.8.0_40]
        at java.awt.Component.dispatchEventImpl(Component.java:4881) [na:1.8.0_40]
        at java.awt.Container.dispatchEventImpl(Container.java:2292) [na:1.8.0_40]
        at java.awt.Component.dispatchEvent(Component.java:4703) [na:1.8.0_40]
        at java.awt.Component.createHierarchyEvents(Component.java:5541) [na:1.8.0_40]
        at java.awt.Container.createHierarchyEvents(Container.java:1443) [na:1.8.0_40]
        at java.awt.Container.createHierarchyEvents(Container.java:1439) [na:1.8.0_40]
        at java.awt.Container.createHierarchyEvents(Container.java:1439) [na:1.8.0_40]
        at java.awt.Container.createHierarchyEvents(Container.java:1439) [na:1.8.0_40]
        at java.awt.Container.createHierarchyEvents(Container.java:1439) [na:1.8.0_40]
        at java.awt.Component.show(Component.java:1622) [na:1.8.0_40]
        at java.awt.Component.show(Component.java:1654) [na:1.8.0_40]
        at java.awt.Component.setVisible(Component.java:1606) [na:1.8.0_40]
        at javax.swing.JComponent.setVisible(JComponent.java:2644) [na:1.8.0_40]
        at javax.swing.JTabbedPane.fireStateChanged(JTabbedPane.java:394) [na:1.8.0_40]
        at javax.swing.JTabbedPane$ModelListener.stateChanged(JTabbedPane.java:270) [na:1.8.0_40]
        at javax.swing.DefaultSingleSelectionModel.fireStateChanged(DefaultSingleSelectionModel.java:132) [na:1.8.0_40]
        at javax.swing.DefaultSingleSelectionModel.setSelectedIndex(DefaultSingleSelectionModel.java:67) [na:1.8.0_40]
        at javax.swing.JTabbedPane.setSelectedIndexImpl(JTabbedPane.java:616) [na:1.8.0_40]
        at javax.swing.JTabbedPane.setSelectedIndex(JTabbedPane.java:591) [na:1.8.0_40]
        at javax.swing.plaf.basic.BasicTabbedPaneUI$Handler.mousePressed(BasicTabbedPaneUI.java:3647) [na:1.8.0_40]
        at java.awt.AWTEventMulticaster.mousePressed(AWTEventMulticaster.java:280) [na:1.8.0_40]
        at java.awt.AWTEventMulticaster.mousePressed(AWTEventMulticaster.java:279) [na:1.8.0_40]
        at java.awt.Component.processMouseEvent(Component.java:6522) [na:1.8.0_40]
        at javax.swing.JComponent.processMouseEvent(JComponent.java:3324) [na:1.8.0_40]
        at java.awt.Component.processEvent(Component.java:6290) [na:1.8.0_40]
        at java.awt.Container.processEvent(Container.java:2234) [na:1.8.0_40]
        at java.awt.Component.dispatchEventImpl(Component.java:4881) [na:1.8.0_40]
        at java.awt.Container.dispatchEventImpl(Container.java:2292) [na:1.8.0_40]
        at java.awt.Component.dispatchEvent(Component.java:4703) [na:1.8.0_40]
        at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4898) [na:1.8.0_40]
        at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4530) [na:1.8.0_40]
        at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4462) [na:1.8.0_40]
        at java.awt.Container.dispatchEventImpl(Container.java:2278) [na:1.8.0_40]
        at java.awt.Window.dispatchEventImpl(Window.java:2750) [na:1.8.0_40]
        at java.awt.Component.dispatchEvent(Component.java:4703) [na:1.8.0_40]
        at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:751) [na:1.8.0_40]
        at java.awt.EventQueue.access$500(EventQueue.java:97) [na:1.8.0_40]
        at java.awt.EventQueue$3.run(EventQueue.java:702) [na:1.8.0_40]
        at java.awt.EventQueue$3.run(EventQueue.java:696) [na:1.8.0_40]
        at java.security.AccessController.doPrivileged(Native Method) [na:1.8.0_40]
        at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75) [na:1.8.0_40]
        at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:86) [na:1.8.0_40]
        at java.awt.EventQueue$4.run(EventQueue.java:724) [na:1.8.0_40]
        at java.awt.EventQueue$4.run(EventQueue.java:722) [na:1.8.0_40]
        at java.security.AccessController.doPrivileged(Native Method) [na:1.8.0_40]
        at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75) [na:1.8.0_40]
        at java.awt.EventQueue.dispatchEvent(EventQueue.java:721) [na:1.8.0_40]
        at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201) [na:1.8.0_40]
        at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116) [na:1.8.0_40]
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105) [na:1.8.0_40]
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101) [na:1.8.0_40]
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93) [na:1.8.0_40]
        at java.awt.EventDispatchThread.run(EventDispatchThread.java:82) [na:1.8.0_40]

```

**Comment by matthewhorridge** [comment] 2016-05-03 19:05
Already fixed.  Duplicate of https://github.com/protegeproject/protege/issues/396.  This wasn't actually an OWLViz problem.

**Closed as completed by matthewhorridge** 2016-05-03 19:05 UTC
